const cartActionTypes = {
  TOGGLE_CART: "TOGGLE_CART",
  CLOSE_CART: "CLOSE_CART",
  ADD_ITEM: "ADD_ITEM",
  INCREASE_ITEM: "INCREASE_ITEM",
  DECREASE_ITEM: "DECREASE_ITEM",
  REMOVE_ITEM: "REMOVE_ITEM",
};

export default cartActionTypes;
